name: gaussian_splatting_mesh
channels:
  - conda-forge
  - defaults
dependencies:
  - plyfile=0.8.1
  - python=3.8
  - pip
  - trimesh==4.0.5
  - SciPy==1.7.3
  - tqdm
  - pip:
    - chumpy==0.70
    - smplx==0.1.28
    - open3d==0.17.0
    - torch==2.0.0
    - torchvision==0.15.1
    - torchaudio==2.0.1
